name: wasmi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  meta: ^1.9.1
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.72.2
  freezed_annotation: ^2.2.0

dev_dependencies:
  ffigen: ^7.2.10
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
