name: wasm_run
description: Web Assembly executor. Uses Rust's wasmtime optimizing runtime or wasmi interpreter.
version: 0.0.1
homepage: https://github.com/juancastillo0/wasm_run

topics:
  - wasm
  - interop
  - runtime
  - interpreter
  - ffi

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  meta: ^1.8.0
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.72.2
  freezed_annotation: ^2.2.0
  wasm_interop: ^2.0.1
  logging: ^1.1.0
  collection: ^1.17.0
  http: ^0.13.5

dev_dependencies:
  ffigen: ^7.2.10
  test: ^1.21.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  very_good_analysis: ^5.0.0
  wasm_run_example:
    path: example
